### ISSUE TITLE
Error in GetCompilationInfoForFile

### ISSUE THREAD

**Issue by matthiasvegh** [martong/ycm_extra_conf.jsondb#1]
In GetCompilationInfoForFile there is a reference to compilation_database_file, which is only initialized if the edited file is a header.
Log output:
Init
database_folder OK
database OK
directory: /home/emtyvgh/sandbox/396986e9c81708dfcbb2
GetCompilationInfoForFile: filename: ./alias.cpp
  File "./.ycm_extra_conf.py", line 15, in FlagsForFile
    return ycm_jsondb_core.FlagsForFile(filename, DirectoryOfThisScript())
  File "/home/emtyvgh/sandbox/396986e9c81708dfcbb2/ycm_jsondb_core.py", line 191, in FlagsForFile
    compilation_info = GetCompilationInfoForFile( filename )
  File "/home/emtyvgh/sandbox/396986e9c81708dfcbb2/ycm_jsondb_core.py", line 174, in GetCompilationInfoForFile
    candidateSrcFile = getFirstEntryOfACompilationDB(compilation_database_file)
UnboundLocalError: local variable 'compilation_database_file' referenced before assignment

As a fix I'd reccomend moving line 147 (compilation_database_file) to above the if IsHeader located on line 133.

**Comment by r0mai** [comment]
PR? :smile:
