### ISSUE TITLE
Headers present in compile_commands.json are not respected

### ISSUE THREAD

**Issue by matthiasvegh** [martong/ycm_extra_conf.jsondb#10]
Usually headers are not present in `compile_commands.json`. If they are however, they should be respected. They can be present in the compilation database if either your headers are built (with `-fsyntax-only`˙for instance), or because you're build environment knows more about how to compile the headers.

At a quick glance, if we add `.hpp` to the SOURCE_EXTENSIONS list the entry is requested.

**Comment by martong** [comment]
Hi Matthias,

Could you please validate the fix on your environment?

Thanks,
Gabor

**Comment by matthiasvegh** [comment]
Looks good to me, thanks! :+1:
