### ISSUE TITLE
ycm_jsondb_core does not find flags for includes

### ISSUE THREAD

**Issue by matthiasvegh** [martong/ycm_extra_conf.jsondb#3]
Hi

If headers are stored in 'incl' folders rather than 'include' folders, the flags returned for the header contain only the additional flags as set by GetAdditionalFlags.
A quick check through the code makes me think that the searchForTranslationUnitWhichIncludesPath method is being used to find my headers, which discards the flags if the regex .`*/include` does not match it. Considering that this is only called if IsHeaderFile returns true, is this strictly necessary?
For my project, I replaced the regex with `.*/incl` and Ycm found the flags correctly.

I'd remove the regex check entirely, but I'm not sure what impacts this would have.
Many thanks!

**Comment by martong** [comment]
Hey Matthias, thanks for your note. Indeed that regex match could be removed. Would you be so kind to create a pull request?

Gabor
